obj-$(CONFIG_UH) 		+= uh_debug_log.o

# app
obj-$(CONFIG_RKP)	+= rkp.o
obj-$(CONFIG_RKP_TEST)		+= rkp_test.o
obj-$(CONFIG_KDP)	+= kdp.o
obj-$(CONFIG_KDP_TEST)		+= kdp_test.o
obj-$(CONFIG_RKP_CFP_JOPP)	+= jopp.o
