# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos9820.dtb

dtbo-$(CONFIG_CAMERA_BEYOND2) += exynos9820-beyond2lte_eur_open_04.dtbo \
	exynos9820-beyond2lte_eur_open_16.dtbo \
	exynos9820-beyond2lte_eur_open_17.dtbo \
	exynos9820-beyond2lte_eur_open_18.dtbo \
	exynos9820-beyond2lte_eur_open_19.dtbo \
	exynos9820-beyond2lte_eur_open_20.dtbo \
	exynos9820-beyond2lte_eur_open_23.dtbo \
	exynos9820-beyond2lte_eur_open_24.dtbo \
	exynos9820-beyond2lte_eur_open_25.dtbo \
	exynos9820-beyond2lte_eur_open_26.dtbo

dtbo-$(CONFIG_CAMERA_BEYOND1) += exynos9820-beyond1lte_eur_open_17.dtbo \
	exynos9820-beyond1lte_eur_open_18.dtbo \
	exynos9820-beyond1lte_eur_open_19.dtbo \
	exynos9820-beyond1lte_eur_open_20.dtbo \
	exynos9820-beyond1lte_eur_open_21.dtbo \
	exynos9820-beyond1lte_eur_open_22.dtbo \
	exynos9820-beyond1lte_eur_open_23.dtbo \
	exynos9820-beyond1lte_eur_open_24.dtbo \
	exynos9820-beyond1lte_eur_open_26.dtbo

dtbo-$(CONFIG_CAMERA_BEYOND0) += exynos9820-beyond0lte_eur_open_17.dtbo \
	exynos9820-beyond0lte_eur_open_18.dtbo \
	exynos9820-beyond0lte_eur_open_19.dtbo \
	exynos9820-beyond0lte_eur_open_20.dtbo \
	exynos9820-beyond0lte_eur_open_22.dtbo \
	exynos9820-beyond0lte_eur_open_24.dtbo \
	exynos9820-beyond0lte_eur_open_25.dtbo

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
