# SPDX-License-Identifier: GPL-2.0

ifdef CONFIG_MODEL_BEYOND0LTE

dtb-y += exynos_b0/exynos9820.dtb
dtbo-y += beyond0lte/exynos9820-beyond0lte_eur_open_17.dtbo
dtbo-y += beyond0lte/exynos9820-beyond0lte_eur_open_24.dtbo
dtbo-y += beyond0lte/exynos9820-beyond0lte_eur_open_19.dtbo
dtbo-y += beyond0lte/exynos9820-beyond0lte_eur_open_25.dtbo
dtbo-y += beyond0lte/exynos9820-beyond0lte_eur_open_20.dtbo
dtbo-y += beyond0lte/exynos9820-beyond0lte_eur_open_18.dtbo
dtbo-y += beyond0lte/exynos9820-beyond0lte_eur_open_22.dtbo

endif

ifdef CONFIG_MODEL_BEYOND1LTE

dtbo-y += beyond1lte/exynos9820-beyond1lte_eur_open_22.dtbo
dtbo-y += beyond1lte/exynos9820-beyond1lte_eur_open_18.dtbo
dtbo-y += beyond1lte/exynos9820-beyond1lte_eur_open_17.dtbo
dtbo-y += beyond1lte/exynos9820-beyond1lte_eur_open_23.dtbo
dtbo-y += beyond1lte/exynos9820-beyond1lte_eur_open_20.dtbo
dtbo-y += beyond1lte/exynos9820-beyond1lte_eur_open_24.dtbo
dtbo-y += beyond1lte/exynos9820-beyond1lte_eur_open_21.dtbo
dtbo-y += beyond1lte/exynos9820-beyond1lte_eur_open_26.dtbo
dtbo-y += beyond1lte/exynos9820-beyond1lte_eur_open_19.dtbo
dtb-y += exynos_b12x/exynos9820.dtb

endif

ifdef CONFIG_MODEL_BEYOND2LTE

dtb-y += exynos_b12x/exynos9820.dtb
dtbo-y += beyond2lte/exynos9820-beyond2lte_eur_open_26.dtbo
dtbo-y += beyond2lte/exynos9820-beyond2lte_eur_open_17.dtbo
dtbo-y += beyond2lte/exynos9820-beyond2lte_eur_open_18.dtbo
dtbo-y += beyond2lte/exynos9820-beyond2lte_eur_open_20.dtbo
dtbo-y += beyond2lte/exynos9820-beyond2lte_eur_open_25.dtbo
dtbo-y += beyond2lte/exynos9820-beyond2lte_eur_open_23.dtbo
dtbo-y += beyond2lte/exynos9820-beyond2lte_eur_open_24.dtbo
dtbo-y += beyond2lte/exynos9820-beyond2lte_eur_open_04.dtbo
dtbo-y += beyond2lte/exynos9820-beyond2lte_eur_open_16.dtbo
dtbo-y += beyond2lte/exynos9820-beyond2lte_eur_open_19.dtbo

endif

ifdef CONFIG_MODEL_BEYONDX

dtbo-y += beyondx/exynos9820-beyondx_eur_open_05.dtbo
dtbo-y += beyondx/exynos9820-beyondx_eur_open_04.dtbo
dtbo-y += beyondx/exynos9820-beyondx_eur_open_03.dtbo
dtbo-y += beyondx/exynos9820-beyondx_eur_open_01.dtbo
dtbo-y += beyondx/exynos9820-beyondx_eur_open_06.dtbo
dtbo-y += beyondx/exynos9820-beyondx_eur_open_07.dtbo
dtbo-y += beyondx/exynos9820-beyondx_eur_open_02.dtbo
dtbo-y += beyondx/exynos9820-beyondx_eur_open_00.dtbo
dtbo-y += beyondx/exynos9820-beyondx_eur_open_08.dtbo
dtb-y += exynos_b12x/exynos9820.dtb

endif

ifdef CONFIG_MODEL_D1

dtb-y += exynos_d12x/exynos9825.dtb
dtbo-y += d1/exynos9820-d1_eur_open_19.dtbo
dtbo-y += d1/exynos9820-d1_eur_open_21.dtbo
dtbo-y += d1/exynos9820-d1_eur_open_18.dtbo
dtbo-y += d1/exynos9820-d1_eur_open_23.dtbo
dtbo-y += d1/exynos9820-d1_eur_open_22.dtbo

endif

ifdef CONFIG_MODEL_D2S

dtbo-y += d2s/exynos9820-d2_eur_open_21.dtbo
dtbo-y += d2s/exynos9820-d2_eur_open_19.dtbo
dtbo-y += d2s/exynos9820-d2_eur_open_18.dtbo
dtbo-y += d2s/exynos9820-d2_eur_open_23.dtbo
dtbo-y += d2s/exynos9820-d2_eur_open_16.dtbo
dtbo-y += d2s/exynos9820-d2_eur_open_17.dtbo
dtbo-y += d2s/exynos9820-d2_eur_open_24.dtbo
dtbo-y += d2s/exynos9820-d2_eur_open_22.dtbo
dtbo-y += d2s/exynos9820-d2_eur_open_02.dtbo
dtbo-y += d2s/exynos9820-d2_eur_open_20.dtbo
dtb-y += exynos_d2s/exynos9825.dtb

endif

ifdef CONFIG_MODEL_D2X

dtbo-y += d2x/exynos9820-d2x_eur_open_20.dtbo
dtbo-y += d2x/exynos9820-d2x_eur_open_18.dtbo
dtbo-y += d2x/exynos9820-d2x_eur_open_24.dtbo
dtbo-y += d2x/exynos9820-d2x_eur_open_23.dtbo
dtbo-y += d2x/exynos9820-d2x_eur_open_19.dtbo
dtbo-y += d2x/exynos9820-d2x_eur_open_21.dtbo
dtbo-y += d2x/exynos9820-d2x_eur_open_22.dtbo
dtbo-y += d2x/exynos9820-d2x_eur_open_16.dtbo
dtbo-y += d2x/exynos9820-d2x_eur_open_02.dtbo
dtbo-y += d2x/exynos9820-d2x_eur_open_17.dtbo
dtb-y += exynos_d12x/exynos9825.dtb

endif


targets += dtbs
DTB_LIST  := $(dtb-y) $(dtbo-y)
always    := $(DTB_LIST)

dtbs: $(addprefix $(obj)/, $(DTB_LIST))

clean-files := *.dtb*
